config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :yurts do
    resources :bookings, only: [:index, :new, :create]
  end

  resources :bookings, only: [:show, :index, :destroy]

  get '/profile', to: "pages#profile"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :yurt

  validates :booked_from, :booked_to, :user_id, :yurt_id, presence: true
  # validates :booked_from, uniqueness: {scope: :yurt}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :yurts
  has_many :bookings, dependent: :destroy
end

app/models/yurt.rb
class Yurt < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :title, :description, :location, :max_capacity, :day_rate, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :destroy, :edit]
  before_action :find_yurt, only: [:create, :new]

  def index
    array = Booking.all
    @bookings = array.select { |booking| booking.user_id == current_user.id }
  end

  def show
    @yurt = @booking.yurt
    @nights = (@booking.booked_to - @booking.booked_from).to_i
    @cost = @nights * @yurt.day_rate

    @markers = [{
      lat: @yurt.latitude,
      lng: @yurt.longitude,
      infoWindow: render_to_string(partial: "yurts/info_window", locals: { yurt: @yurt }),
      image_url: helpers.asset_url('image.png')
    }]
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking.id), alert: "Update successful"
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.yurt = @yurt
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking.id), alert: "Booking successful"
    else
      redirect_to yurt_path(@yurt.id), alert: "Booking failed"
    end
  end

  def destroy
    @booking.destroy
    redirect_to profile_path, alert: "Cancellation successful - Booking cancelled"
  end

  private

  def booking_params
    params.require(:booking).permit(:booked_from, :booked_to, :total_cost, :user_id, :yurt_id)
  end

  def find_yurt
    @yurt = Yurt.find(params[:yurt_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @yurts = Yurt.all
  end

  def profile
    @user = current_user
    @yurts = Yurt.where(user: @user)
    @bookings = Booking.where(user: @user)
  end
end

app/controllers/yurts_controller.rb
class YurtsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_yurt, only: [:show, :destroy]

  def index
    @yurts = Yurt.all
    @markers = @yurts.geocoded.map do |yurt|
      {
        lat: yurt.latitude,
        lng: yurt.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { yurt: yurt }),
        image_url: helpers.asset_url('image.png')
      }
    end
  end

  def show
    @markers = [{
      lat: @yurt.latitude,
      lng: @yurt.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { yurt: @yurt }),
      image_url: helpers.asset_url('image.png')
    }]
  end

  def new
    @yurt = Yurt.new
  end

  def create
    @yurt = Yurt.new(yurt_params)
    @yurt.user = current_user
    if @yurt.save
      redirect_to yurt_path(@yurt), alert: "Creation successful"
    else
      render :new
    end
  end

  def edit
    @yurt = Yurt.find(params[:id])
  end

  def update
    @yurt = Yurt.find(params[:id])
    @yurt.update(yurt_params)
    if @yurt.save
      redirect_to yurt_path
    else
      render :new
    end
  end

  def destroy
    @yurt.destroy
    redirect_to yurts_path, alert: "Deletion successful - Yurt deleted"
  end

  private

  def find_yurt
    @yurt = Yurt.find(params[:id])
  end

  def yurt_params
    params.require(:yurt).permit(:title, :description, :location, :max_capacity, :day_rate, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<h2>Book your yurt experience</h2>

<% if yurt.photo.attached? %>
  <%= cl_image_tag yurt.photo.key, height: 400, width: 600, crop: :fill %>
<% end %>
<h3><%= yurt.title %></h3>
<div class="form-yurt-description"><%= yurt.description %></div>
<p><%= yurt.location %></p>
<p>Price per night: <strong>£<%= yurt.day_rate %></strong></p>
<hr>
<%= simple_form_for [yurt, booking] do |f| %>
  <%= f.input :booked_from, as: :date, html5: true, label: 'From' %>
  <%= f.input :booked_to, as: :date, html5: true, label: 'To' %>
  <%= f.submit "Book this yurt!", class: "button" %>
 <% end %>

app/views/bookings/edit.html.erb
<div class="form-container">
  <%= render "form", booking: @booking, yurt: @yurt %>
</div>

app/views/bookings/index.html.erb
<div class="bookings">
  <h1>Your Bookings:</h1>
    <div class="row">
      <div class="col-sm-12">
        <% @bookings.each do |booking| %>
          <h2><%= booking.yurt.title %></h2>
          <ul>
            <li><%= booking.yurt.description %></li>
            <li><%= booking.booked_from %> - <%= booking.booked_to %></li>
          </ul>
          <p><%= link_to 'View booking details', booking_path(booking.id) %></p>
          <p><%= link_to "Delete",
            booking_path(booking),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p>
        <% end %>
      </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="form-container">
  <%= render "form", booking: @booking, yurt: @yurt %>
</div>

app/views/bookings/show.html.erb
<div class="booking-container">
  <div class= "yurts-container">
    <div class="booking-card col-6">
      <h1 class="booking-header">Your booking</h1>
      <% if @booking.yurt.photo.attached? %>
        <%= cl_image_tag @booking.yurt.photo.key, class:"yurt-image", crop: :fill %>
      <% else %>
        <p>No image attached</p>
      <% end %>
      <div class="booking-yurt-details">
        <h2><%= @booking.yurt.title %></h2>
        <div class="booking-yurt-description"><%= @booking.yurt.description %></div>
        <p>Location: <%= @booking.yurt.location %></p>
        <p>Price: £<%= @booking.yurt.day_rate %> / night</p>
      </div>
      <hr>
      <h3>Your stay</h3>
      <ul class="show-booking-details">
        <li>From <strong><%= @booking.booked_from.strftime("%a %e %b %y") %></strong> to
        <strong><%= @booking.booked_to.strftime("%a %e %b %y") %></strong></li>
        <li>Nights: <%= @nights %></li>
        <li>Total cost: £<%= @cost %></li>
      </ul>
      <hr>
      <p><%= link_to 'Cancel this booking', booking_path(@booking.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <p><%= link_to 'Back', yurt_path(@booking.yurt_id) %></p>
    </div>
  </div>

  <div class="map-container col-6">
    <div id="map"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAYurtProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&family=Raleway:wght@100;300;400;500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="yield-container">
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header">
  <div class="hero-image">
    <div class="hero-text">
      <h1>Rent a Yurt</h1>
<!--       <p>Experience the best yurts in the world</p> -->
      <p><span id="banner-typed-text"></span></p>
      <%= link_to 'Find a yurt', yurts_path, class: "button" %>
      <% if user_signed_in? %>
      <%= link_to 'Your profile', profile_path, class: "button" %>
      <% else %>
      <%= link_to 'Become a host', new_user_registration_path, class: "button" %>
      <% end %>
    </div>
  </div>
</div>

<div class="subheading-text">
    <h3>Featured Yurts</h3>
</div>
<!-- carousel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for carousel items -->
    <div class="carousel-inner">
        <div class="carousel-item active">
          <%= render "shared/yurt_row", yurts: @yurts[0..2] %>
        </div>
        <div class="carousel-item">
          <%= render "shared/yurt_row", yurts: @yurts[3..5] %>
        </div>
        <div class="carousel-item">
          <%= render "shared/yurt_row", yurts: @yurts[6..8] %>
        </div>
    </div>
    <!-- Carousel controls -->
    <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
        <i class="fas fa-chevron-left arrow"></i>
    </a>
    <a class="carousel-control-next" href="#myCarousel" data-slide="next">
        <i class="fas fa-chevron-right arrow"></i>
    </a>
</div>
<!-- carousel -->

app/views/pages/profile.html.erb
<div class="profile-container">

  <div>
    <div>
      <div class = "profile-page-header">
        <h3>Your Yurt Listings</h3>
      </div>
      <div class="profile-page-row">
        <% if @yurts.empty? %>
          <%= link_to 'Become a host!', new_yurt_path, class: "button"  %>
        <% else %>
          <% @yurts.each do |yurt| %>
            <div class="profile-page-column">
              <div class="yurt-card-small">
                <% if yurt.photo.attached? %>
                  <%= cl_image_tag yurt.photo.key, width: 240, height: 240, crop: :fill %>
                <% else %>
                  <p>No image attached</p>
                <% end %>

                <div class="yurt-card-info">
                  <h3><%= yurt.title %></h3>
                  Sleeps <%= yurt.max_capacity %>
                  <div class="yurt-card-info-inline">
                    £<%= yurt.day_rate %> / night

                    <%= link_to 'More info', yurt_path(yurt), class: "button"  %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div>
    <div>
      <div class="profile-page-header">
        <h3>Your Bookings</h3>
      </div>
      <div>
        <div class="bookings">
          <div class="profile-page-row">
            <% if @bookings.empty? %>
              <div>
                <%= link_to 'Find a yurt', yurts_path, class: "button"  %>
              </div>
            <% else %>
              <% @bookings.each do |booking| %>
                <div class="column">
                  <div class="card" id="booking-card">
                    <% if booking.yurt.photo.attached? %>
                      <%= cl_image_tag booking.yurt.photo.key, width: 240, height: 240, crop: :fill %>
                    <% else %>
                      <p>No image attached</p>
                    <% end %>

                    <div class="booking-card-info">
                      <h3><%= booking.yurt.title %></h3>

                      <div class="booking-dates">
                        <strong><%= booking.booked_from.strftime("%a %e %b %y") %></strong> to <strong><%= booking.booked_to.strftime("%a %e %b %y") %></strong>
                      </div>
                      <%= link_to 'View booking details', booking_path(booking.id), class: "button" %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div>
    <div>
      <div class="profile-page-header">
        <h3>Your Details</h3>
      </div>
      <div class = "details-container">
          <p>Email: <%= @user.email %></p>
          <p>First name: <%= @user.first_name %></p>
          <p>Last name: <%= @user.last_name %></p>
          <%= link_to edit_user_registration_path do %>
            Edit info <i class="fas fa-edit"></i>
          <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<%#= added standard flashes/alerts from lewagon %>
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <!--Footer-->
<footer>

  <div class = "footer-grid">

    <div class = "footer-grid-element-1">

      <ul class="icons">
        <i class="fab fa-twitter"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-facebook-f"></i>
      </ul>

    </div>

    <div class="footer-grid-element-2">

       <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>

    </div>

    <div class="footer-grid-element-3">

      <p class="copyright">© 2021 RentAYurt, Inc. All rights reserved</p>

    </div>

  </div>

</footer>

app/views/shared/_navbar.html.erb
<%#= added standard navbar from lewagon %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dlxlmoq7d/image/upload/v1614101366/YurtLogo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "View Yurts", yurts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="tent-dropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-campground"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Host your Yurt", new_yurt_path, class: "dropdown-item" %>
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="tent-dropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-campground"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View Yurts", yurts_path, class: "dropdown-item" %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Become a Host", new_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_yurt_row.html.erb
<div class ="featured">
  <div class="row">
    <% yurts.each do |yurt| %>
      <div class="column">
        <div class="yurt-card-small">
          <% if yurt.photo.attached? %>
            <%= cl_image_tag yurt.photo.key, width: 240, height: 240, crop: :fill %>
          <% else %>
            <p>No image attached</p>
          <% end %>

          <div class="yurt-card-info">
            <h3><%= yurt.title.truncate(20) %></h3>
            Sleeps <%= yurt.max_capacity %>
            <div class="yurt-card-info-inline">
              £<%= yurt.day_rate %> / night

              <%= link_to 'More Info', yurt_path(yurt), class: 'button' %>
            </div>
          </div>


        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/yurts/_form.html.erb
  <h2>Your yurt</h2>
  <%= simple_form_for yurt do |f| %>
    <%= f.input :title, placeholder: 'e.g.: Pretty 10-man yurt'  %>
    <%= f.input :description, label: 'Description of your tent and its features' %>
    <%= f.input :photo, as: :file, label: 'Upload your photo' %>
    <%= f.input :location, label: 'Where is it?', inner_html: { id: 'yurt_location' } %>
    <%= f.input :max_capacity, label: 'How many people?' %>
    <%= f.input :day_rate, label: 'What is the price for one night?' %>
    <%= f.submit "List your yurt!", class: "button" %>
  <% end %>

app/views/yurts/_info_window.html.erb
<div class="info-window">
  <%= cl_image_tag yurt.photo.key, width: 200, height: 200, crop: :fill %>
  <h4><%= yurt.title %></h4>
  <p><%= yurt.location %></p>
  <p>Max capacity: <%= yurt.max_capacity %></p>
  <p>Day rate : £<%= yurt.day_rate %></p>
</div>

app/views/yurts/_show_card.html.erb
<div class="show-card">
  <div id="yurt-image">
    <% if @yurt.photo.attached? %>
      <%= cl_image_tag yurt.photo.key, class:"yurt-image", crop: :fill %>
    <% else %>
      <p>No image attached</p>
    <% end %>
  </div>
  <div class="yurt-card-text">
    <div class="yurt-title"><h2><%= yurt.title %></h2></div>
    <div id="yurt-info">
      <div class="location"><p><%= yurt.location %></p></div>
      <div class="description"><%= yurt.description %></div>
      <div class="capacity-cost">
        <div class="capacity"><p>Max Capacity: <%= yurt.max_capacity %></p></div>
        <div class="day-rate"><p>Day rate: £<%= yurt.day_rate %></p></div>
      </div>

      <div class="host-email"><p>Host: <%= yurt.user.email %></p></div>
    </div>

    <div class="show-links">
     <%= link_to 'Book this yurt', new_yurt_booking_path(yurt), class:"button" %>
    <%= link_to 'Back to yurts', yurts_path %>
    </div>
  </div>
</div>

app/views/yurts/edit.html.erb
<div class="form-container">
  <%= render "form", yurt: @yurt %>
</div>

app/views/yurts/index.html.erb
<div class="yurt-index">
    <div class="yurts-container">
      <div class="row">
        <% @yurts.each do |yurt| %>
          <div class="col-12">
            <div class="yurt-card">
              <% if yurt.photo.attached? %>
                <%= cl_image_tag yurt.photo.key, class: 'yurt-card-image', crop: :fill %>
              <% else %>
                <div style="width: 240px, height: 240px">
                    <i class="fas fa-square"></i>
                    <p>No photo attached</p>
                </div>
              <% end %>
              <div class="yurt-card-body">
                <h5 class="card-title"><%= yurt.title %></h5>
                <div class="card-location"><%= yurt.location %></div>
                <div class="card-description"><%= yurt.description.truncate(120, separator: ' ') %></div>
                <div class="detailsholder">
                  <div class="yurt-details">
                    <div class="card-text">Max Capacity: <%= yurt.max_capacity %></div>
                    <div class="day-rate"> Day rate: £<%= yurt.day_rate %></div>
                  </div>
                  <div class="yurt-link" >
                    <%= link_to 'More info', yurt_path(yurt.id), class: "button" %>
                  </div>
                </div>
              </div>

            </div>
          </div>
        <% end %>
      </div>
    </div>

  <div class="map-container">
    <div id="map"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/yurts/new.html.erb
<div class="form-container">
  <%= render "form", yurt: @yurt %>
</div>

app/views/yurts/show.html.erb
<div class="show-page">


  <div class="yurts-container">
     <%= render 'show_card', yurt: @yurt %>

      <% if current_user == @yurt.user %>
        <div class="yurt-host-edit">
          <div class="edit-links">
            <h5>Yurt Host actions:</h5>
            <div class="yurt-edit">
              <%= link_to edit_yurt_path @yurt do %>
                Update yurt details <i class="fas fa-edit"></i>
              <% end %>
            </div>
            <div class="yurt-delete">
              <%= link_to 'Delete your yurt', yurt_path(@yurt.id), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="yurt-host-edit">
          <p>Please contact the host for more information about this yurt.</p>
        </div>
      <% end %>
  </div>

  <div class="map-container col-6">
    <div id="map"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>